#!/bin/bash
# experiment:24_exp_sGuard

dataset_name_exp_sGuard="sGuard_dataset_in_groups"
contract_info_csv_name_prefix="contracts_info_group"
contract_group_name_prefix="contracts_10_group"
group_start_index=1
group_end_index=480
p1_depth_limit=1
export dataset_name_exp_sGuard contract_info_csv_name_prefix contract_group_name_prefix group_start_index group_end_index p1_depth_limit



cli_timeout=1000
tool_timeout=900
solver_timeout=10000
execution_times=3
export cli_timeout tool_timeout solver_timeout execution_times


container_run_script_compile="run_compile_solc_for_a_group.sh"
container_run_script_mythril="run_mythril_v0.23.22_bin_for_a_group.sh"
container_run_script_smartian="run_smartian_for_a_group.sh"
container_run_script_smartExecutor="run_smartExecutor_v4.0_bin_for_a_group.sh"
 
export container_run_script_compile container_run_script_mythril container_run_script_smartian container_run_script_smartExecutor

